### ISSUE TITLE
about the when directive

### ISSUE THREAD

**Issue by eko234** [eburghar/kakship#2]
Hi, I'm trying out your plugin, and was wondering if there is a way to update a segment every 3 seconds or something like that.

thanks :)

**Comment by eburghar** [comment]
Hi eko234,

It's kakoune which decides when to evaluate the status line. We have no control on that. if you use a %sh{} expansion (like the kaktime segment in the README), the modline is interpreted every second, otherwise the status line is reinterpreted generally when you do something in the editor (which is coherent since the modline contains information about the current mode and the cursor position).

The when directive is a starship directive, not a kakoune one. It just tells starship on which condition it should insert the segment in the final status line.
